# Generated by Django 3.2 on 2022-04-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='modified_time')),
                ('name', models.CharField(error_messages={'unique': 'a product with that name exists'}, max_length=150, unique=True, verbose_name='name')),
                ('price', models.SmallIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
